import type { Metadata } from "next";
import DashboardNav from "../components/nav/app_nav/dashboard_nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <DashboardNav />
      <main className="flex flex-col flex-grow">{children}</main>
    </div>
  );
}
